# Generated by Django 5.0.4 on 2025-06-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileview",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
    ]
